# Generated by Django 5.1.1 on 2025-07-09 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional duration in hours (e.g., 1.5 for 1 hour 30 minutes)', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Duration in hours (e.g., 1.5 for 1 hour 30 minutes)', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days'),
        ),
    ]
