# Generated by Django 5.1.1 on 2025-07-09 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_duration_hours_event_end_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('event', 'email')},
        ),
    ]
