# Generated by Django 5.1.1 on 2025-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attendee_confirmed_at_attendee_phone_attendee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether event appears in public listings'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes',
            field=models.DateTimeField(blank=True, help_text='When registration closes (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens',
            field=models.DateTimeField(blank=True, help_text='When registration opens (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.CharField(choices=[('open', 'Open Registration'), ('invitation_only', 'Invitation Only'), ('approval_required', 'Approval Required')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether registrations need manual approval'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
