# Generated by Django 5.1.1 on 2025-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset_verifyregistereduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('org_owner', 'Organization Owner'), ('org_admin', 'Organization Admin'), ('member', 'Member')], default=('member', 'Member'), max_length=50),
        ),
    ]
