# Generated by Django 5.1.1 on 2025-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinvitation',
            name='is_registration_approved',
        ),
    ]
